name: Generate Template File
description: A Github Action for generating files from templates
inputs:
  template:
    description: Template file to use
    required: true
  parameters:
    description: Parameters to use when generating from the template
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.template }}
    - ${{ inputs.parameters }}
branding:
  icon: align-center
  color: green