name: Project name
description: Project description
inputs:
  opt1:
    description: Description for opt1
    required: false
    default: opt
  opt2:
    description: Description for opt2
    required: false
    default: opt
  opt3:
    description: Description for opt3
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.opt1 }}
    - ${{ inputs.opt2 }}
    - ${{ inputs.opt3 }}
branding:
  icon: align-center
  color: green