
on: workflow_dispatch

name: Generate file from template

jobs:
  test:
    name: Generate file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Generate file
        uses: jmgilman/actions-template-file@v1
        with:
          template: test.tmp
          parameters: |
            {
              "param1": "value1",
              "param2": 2
            }